=== dkomar/telefonica-ifspec/CDR.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <!-- callcase contains a one or more <CDR> elements and a @name -->
  <xs:element name="callcase">
    <xs:complexType>
      <xs:sequence minOccurs="1" maxOccurs="unbounded">
        <xs:element name="CDR" type="XMLCDRType"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  
  <!-- the <CDR> element -->
  <xs:complexType name="XMLCDRType">
    <xs:sequence>
      <xs:element name="layer" type="XMLLayerType" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="callpartid" type="NonEmptyString-Type" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="XMLLayerType">
    <xs:sequence>
      <xs:element name="mMTelServiceRecord" type="MMTelServiceRecord" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="from" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="MTAS"/>
          <xs:enumeration value="BWAS"/>
          <xs:enumeration value="S-CSCF"/>
          <xs:enumeration value="E-CSCF"/>
          <xs:enumeration value="ngIN-AS"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="MMTelServiceRecord">
    <xs:sequence>
      <xs:element name="mMTelRecord" type="MMTelRecord" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="MMTelRecord">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="1" name="recordType" type="recordType-Type"/>
      <xs:element minOccurs="1" maxOccurs="1" name="role-of-Node">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:enumeration value="0"/>
             <!-- originating -->
            <xs:enumeration value="1"/>
             <!-- terminating -->
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element minOccurs="1" maxOccurs="1" name="session-Id" type="xs:string"/>
      <xs:element minOccurs="1" maxOccurs="unbounded" name="list-Of-Calling-Party-Address" type="InvolvedParty-Type"/>
      <xs:element minOccurs="1" maxOccurs="1" name="called-Party-Address" type="InvolvedParty-Type"/>
      <xs:element minOccurs="1" maxOccurs="1" name="serviceRequestTimeStamp" type="TimeStamp"/>
      <xs:element minOccurs="1" maxOccurs="1" name="serviceRequestTimeStampFraction" type="MilliSecondsType"/>
      <xs:element minOccurs="1" maxOccurs="1" name="serviceDeliveryStartTimeStamp" type="TimeStamp"/>
      <xs:element minOccurs="1" maxOccurs="1" name="serviceDeliveryStartTimeStampFraction" type="MilliSecondsType"/>
      <xs:element minOccurs="1" maxOccurs="1" name="serviceDeliveryEndTimeStamp" type="TimeStamp"/>
      <xs:element minOccurs="1" maxOccurs="1" name="serviceDeliveryEndTimeStampFraction" type="MilliSecondsType"/>
      <xs:element name="interOperatorIdentifiers">
        <xs:complexType>
          <xs:sequence minOccurs="0" maxOccurs="1">
            <xs:element name="originatingIOI" type="xs:string"/>
            <xs:element name="terminatingIOI" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="causeForRecordClosing">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:enumeration value="0"/>
             <!-- serviceDeliveryEndSuccessfully -->
            <xs:enumeration value="1"/>
             <!-- unSuccessfulServiceDelivery -->
            <xs:enumeration value="3"/>
             <!-- timeLimit -->
            <xs:enumeration value="4"/>
             <!-- serviceChange -->
            <xs:enumeration value="5"/>
             <!-- managementIntervention -->
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="incomplete-CDR-Indication" type="xs:string"/>
      <xs:element name="iMS-Charging-Identifier" type="xs:string"/>
      <xs:element name="list-Of-SDP-Media-Components" type="list-Of-SDP-Media-Components-Type"/>
      <xs:element name="serviceReasonReturnCode" type="xs:integer"/>
      <xs:element name="recordExtensions" type="recordExtensions-Type"/>
      <xs:element name="Access-Network-Information" type="xs:string"/>
      <xs:element name="serviceContextID">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="([0-9]+.)?[0-9]+@3gpp.org"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:sequence minOccurs="1" maxOccurs="unbounded">
        <xs:element name="list-of-subscription-ID">
          <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="1">
              <xs:element name="subscriptionIDType">
                <xs:simpleType>
                  <xs:restriction base="xs:integer">
                    <xs:enumeration value="0"/>
                     <!-- END_USER_E164 -->
                    <xs:enumeration value="1"/>
                     <!-- END_USER_IMSI -->
                    <xs:enumeration value="2"/>
                     <!-- END_USER_SIP_URI -->
                    <xs:enumeration value="3"/>
                     <!-- END_USER_NAI -->
                    <xs:enumeration value="4"/>
                     <!-- END_USER_PRIVATE -->
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="subscriptionIDData" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:element name="iMSCommunicationServiceIdentifier" type="xs:string"/>
      <xs:element name="numberPortabilityRouting" type="xs:string"/>
      <xs:element name="transit-IOI-List" type="xs:string"/>
      <!--
      <xs:element name="userLocationInformation">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="LCS-Client-ID" type="xs:string"/>
            <xs:element name="Location-Type" type="xs:string"/>
            <xs:element name="Location-Estimate" type="xs:string"/>
            <xs:element name="Positioning-Data" type="xs:string"/>
            <xs:element name="IMSI" type="xs:string"/>
            <xs:element name="MSISDN" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      -->
      <xs:element name="mSTimeZone" type="xs:string"/>
       <!-- check -->
      <xs:sequence minOccurs="1" maxOccurs="unbounded">
        <xs:element name="serviceSpecificInfo">
          <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="1">
              <xs:element name="serviceSpecificType" type="xs:integer"/>
              <xs:element name="serviceSpecificData" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:element minOccurs="1" maxOccurs="1" name="requested-Party-Address" type="InvolvedParty-Type"/>
      <xs:element minOccurs="1" maxOccurs="unbounded" name="list-Of-Called-Asserted-Identity" type="InvolvedParty-Type"/>
      <xs:element minOccurs="1" maxOccurs="1" name="mMTelInformation" type="mMTelInformation-Type"/>
    </xs:sequence>
  </xs:complexType>
  
  
  
  <xs:complexType name="list-Of-SDP-Media-Components-Type">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="media-Components-List" type="media-Components-List-Type"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="media-Components-List-Type">
    <xs:sequence minOccurs="1" maxOccurs="1">
      <xs:element name="sIP-Request-Timestamp" type="TimeStamp"/>
      <xs:element name="sIP-Request-Timestamp-Fraction" type="MilliSecondsType"/>
      <xs:element name="sIP-Response-Timestamp" type="TimeStamp"/>
      <xs:element name="sIP-Response-Timestamp-Fraction" type="MilliSecondsType"/>
      <xs:element name="sDP-Media-Components" type="sDP-Media-Components-Type"/>
      <xs:element name="mediaInitiatorFlag">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:enumeration value="0"/>
             <!-- called party has requested the session modification -->
            <xs:enumeration value="1"/>
             <!-- calling party has requested the session modification -->
            <xs:enumeration value="2"/>
             <!-- unknown participiant has requested the session modification -->
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="sDP-Session-Description" type="xs:string"/>
      <xs:element name="sDP-Type">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:enumeration value="0"/>
             <!-- SDP Offer -->
            <xs:enumeration value="1"/>
             <!-- SDP Answer -->
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="sDP-Media-Components-Type">
    <xs:sequence minOccurs="1" maxOccurs="1">
      <xs:element name="sDP-Media-Name" type="xs:string"/>
      <xs:element name="sDP-Media-Description" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="recordExtensions-Type">
    <xs:sequence minOccurs="1" maxOccurs="1">
      <xs:element name="bW-service-provider" type="xs:string"/>
      <xs:element name="bW-user-Number" type="xs:string"/>
      <xs:element name="bW-dialed-Digits" type="xs:string"/>
      <xs:element name="bW-call-Category" type="xs:string"/>
      <xs:element name="bW-network-Translated-Number" type="xs:string"/>
      <xs:element name="bW-codec" type="xs:string"/>
      <xs:element name="bW-access-Callid" type="xs:string"/>
      <xs:element name="bW-group" type="xs:string"/>
      <xs:element name="bW-original-Called-Number" type="xs:string"/>
      <xs:element name="bW-redirecting-Number" type="xs:string"/>
      <xs:element name="bW-userId" type="xs:string"/>
      <xs:element name="bW-other-Party-Name" type="xs:string"/>
      <xs:element name="eMM-on-net-flag" type="xs:string"/>
      <xs:element name="eMM-on-platform-flag" type="xs:string"/>
      <xs:element name="eMM-faxmail-flag" type="xs:string"/>
      <xs:element name="eMM-voicemail-flag" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="mMTelInformation-Type">
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:element name="listOfSupplServices" type="listOfSupplServices-Type"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="listOfSupplServices-Type">
    <xs:sequence minOccurs="1" maxOccurs="1">
      <xs:element name="serviceType">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:enumeration value="0"/>
             <!-- Originating Identification Presentation (OIP) -->
            <xs:enumeration value="1"/>
             <!-- Originating Identification Restriction (OIR) -->
            <xs:enumeration value="2"/>
             <!-- Terminating Identification Presentation (TIP) -->
            <xs:enumeration value="3"/>
             <!-- Terminating Identification Restriction (TIR) -->
            <xs:enumeration value="4"/>
             <!-- Communication HOLD (HOLD) -->
            <xs:enumeration value="5"/>
             <!-- Communications Barring (CB) -->
            <xs:enumeration value="6"/>
             <!-- Communication Diversion (CDIV) -->
            <xs:enumeration value="7"/>
             <!-- Communication Diversion Notification (CDIVN) -->
            <xs:enumeration value="8"/>
             <!-- Communication Waiting (CW) -->
            <xs:enumeration value="9"/>
             <!-- Message Waiting Indication (MWI) -->
            <xs:enumeration value="10"/>
             <!-- Conference (CONF) -->
            <xs:enumeration value="11"/>
             <!-- Flexible Alerting (FA) -->
            <xs:enumeration value="12"/>
             <!-- Completion of Communication to Busy Subscriber (CCBS) -->
            <xs:enumeration value="13"/>
             <!-- Completion of Communications on No Reply (CCNR) -->
            <xs:enumeration value="14"/>
             <!-- Malicious Communication Identification (MCID) -->
            <xs:enumeration value="15"/>
             <!-- Customized Alerting Tone (CAT)  -->
            <xs:enumeration value="16"/>
             <!-- Closed User Group (CUG) -->
            <xs:enumeration value="17"/>
             <!-- Personal Network management -->
            <xs:enumeration value="18"/>
             <!-- Customized Ringing Signal -->
            <xs:enumeration value="19"/>
             <!-- Advice of Charge (AoC) -->
            <xs:enumeration value="26221"/>
             <!-- Communication Diversion Fixed To Mobile -->
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="serviceMode">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:enumeration value="0"/>
             <!-- Communication Forwarding Unconditional (CFU) -->
            <xs:enumeration value="1"/>
             <!-- Communication Forwarding Busy (CFB) -->
            <xs:enumeration value="2"/>
             <!-- Communication Forwarding No Reply (CRNR) -->
            <xs:enumeration value="3"/>
             <!-- Communication Forwarding on Not Logged-In (CFNL) -->
            <xs:enumeration value="4"/>
             <!-- Communication Deflection (CD) -->
            <xs:enumeration value="5"/>
             <!-- Communication Forwarding on Subscriber Not Reachable (CFNRc) -->
            <xs:enumeration value="6"/>
             <!-- Incoming Call Barring (ICB) -->
            <xs:enumeration value="7"/>
             <!-- Outgoing Call Barring (OCB) -->
            <xs:enumeration value="8"/>
             <!-- Anonymous Communication Rejection (ACR) -->
            <xs:enumeration value="9"/>
             <!-- Blind Transfer -->
            <xs:enumeration value="10"/>
             <!-- Consultative Transfer -->
            <xs:enumeration value="11"/>
             <!-- Three-Party (3PTY) -->
            <xs:enumeration value="12"/>
             <!-- Advice of Charge -S (AoC-S) -->
            <xs:enumeration value="13"/>
             <!-- Advice of Charge -D (AoC-D) -->
            <xs:enumeration value="14"/>
             <!-- Advice of Charge -E (AoC-E) -->
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="associated-Party-Address" type="InvolvedParty-Type"/>
      <xs:element name="serviceId" type="xs:string"/>
      <xs:element name="changeTime" type="TimeStamp"/>
      <xs:element name="participantActionType">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:enumeration value="0"/>
             <!-- CREATE_CONF -->
            <xs:enumeration value="1"/>
             <!-- JOIN_CONF -->
            <xs:enumeration value="2"/>
             <!-- INVITE_INTO_CONF -->
            <xs:enumeration value="3"/>
             <!-- QUIT_CONF -->
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:simpleType name="recordType-Type">
    <xs:restriction base="xs:integer">
      <xs:enumeration value="83"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="TimeStamp">
    <xs:restriction base="xs:string">
      <!-- YYMMDDhhmmssShhmm where S is a sign (+/-) -->
      <xs:pattern value="[0-9]{12}[+-][0-9]{4}"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="InvolvedParty-Type">
    <xs:choice minOccurs="1" maxOccurs="1">
      <xs:element name="sip">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="(sip:[^@]*@.*|unknown)"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="tel">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="tel:\+?[0-9]*"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="urn" type="xs:string"/>
      <xs:element name="e164" type="xs:string"/>
    </xs:choice>
  </xs:complexType>
  
  <xs:simpleType name="MilliSecondsType">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="999"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="NonEmptyString-Type">
    <xs:restriction base="xs:string">
      <xs:pattern value="..*"/>
    </xs:restriction>
  </xs:simpleType>
  
</xs:schema>

=== dkomar/telefonica-ifspec/CDR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Usage:
- indentation required! 2 spaces, no tab characters!
-->
<callcase name="whatever" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CDR.xsd">
  <CDR callpartid="1">
    <layer from="S-CSCF">
      <mMTelServiceRecord>
        <mMTelRecord>

          <!-- always 83 -->
          <recordType>83</recordType>

          <!-- 0 for originating, 1 for terminating -->
          <role-of-Node>0</role-of-Node>

          <!-- some fake sessionid -->
          <session-Id></session-Id>

          <!-- TEL or SIP URI, multiple occurences allowed -->
          <list-Of-Calling-Party-Address>
            <tel>tel:1234</tel>
          </list-Of-Calling-Party-Address>
          <list-Of-Calling-Party-Address>
            <tel>tel:+4912312312341234</tel>
          </list-Of-Calling-Party-Address>
          <list-Of-Calling-Party-Address>
            <sip>sip:blablabla@domain.de</sip>
          </list-Of-Calling-Party-Address>
          <called-Party-Address>
            <tel>tel:+49123123123</tel>
          </called-Party-Address>
          
          <serviceRequestTimeStamp>031231235959+0000</serviceRequestTimeStamp>
          <serviceRequestTimeStampFraction>239</serviceRequestTimeStampFraction>
          <serviceDeliveryStartTimeStamp>031231235959+0000</serviceDeliveryStartTimeStamp>
          <serviceDeliveryStartTimeStampFraction>923</serviceDeliveryStartTimeStampFraction>
          <serviceDeliveryEndTimeStamp>031231235959+0000</serviceDeliveryEndTimeStamp>
          <serviceDeliveryEndTimeStampFraction>129</serviceDeliveryEndTimeStampFraction>
          <interOperatorIdentifiers>
            <originatingIOI></originatingIOI>
            <terminatingIOI></terminatingIOI>
          </interOperatorIdentifiers>
          <causeForRecordClosing>0</causeForRecordClosing>
          <incomplete-CDR-Indication/>
          <iMS-Charging-Identifier></iMS-Charging-Identifier>
          <list-Of-SDP-Media-Components>
            <media-Components-List>
              <sIP-Request-Timestamp>031231235959+0000</sIP-Request-Timestamp>
              <sIP-Request-Timestamp-Fraction>234</sIP-Request-Timestamp-Fraction>
              <sIP-Response-Timestamp>031231235959+0000</sIP-Response-Timestamp>
              <sIP-Response-Timestamp-Fraction>575</sIP-Response-Timestamp-Fraction>
              <sDP-Media-Components>
                <sDP-Media-Name></sDP-Media-Name>
                <sDP-Media-Description></sDP-Media-Description>
              </sDP-Media-Components>
              <mediaInitiatorFlag>0</mediaInitiatorFlag>
              <sDP-Session-Description></sDP-Session-Description>
              <sDP-Type>0</sDP-Type>
            </media-Components-List>
          </list-Of-SDP-Media-Components>
          <serviceReasonReturnCode>0</serviceReasonReturnCode>
          <recordExtensions>
            <bW-service-provider>est</bW-service-provider>
            <bW-user-Number>test</bW-user-Number>
            <bW-dialed-Digits>test</bW-dialed-Digits>
            <bW-call-Category>test</bW-call-Category>
            <bW-network-Translated-Number>test</bW-network-Translated-Number>
            <bW-codec>test</bW-codec>
            <bW-access-Callid>test</bW-access-Callid>
            <bW-group>test</bW-group>
            <bW-original-Called-Number>est</bW-original-Called-Number>
            <bW-redirecting-Number>test</bW-redirecting-Number>
            <bW-userId>test</bW-userId>
            <bW-other-Party-Name>test</bW-other-Party-Name>
            <eMM-on-net-flag>test</eMM-on-net-flag>
            <eMM-on-platform-flag>test</eMM-on-platform-flag>
            <eMM-faxmail-flag>test</eMM-faxmail-flag>
            <eMM-voicemail-flag>test</eMM-voicemail-flag>
          </recordExtensions>
          <Access-Network-Information></Access-Network-Information>
          <serviceContextID>11.32275@3gpp.org</serviceContextID>
          <list-of-subscription-ID>
            <subscriptionIDType>0</subscriptionIDType>
            <subscriptionIDData>+491525222343234</subscriptionIDData>
          </list-of-subscription-ID>
          <list-of-subscription-ID>
            <subscriptionIDType>2</subscriptionIDType>
            <subscriptionIDData>sip:user@domain.com</subscriptionIDData>
          </list-of-subscription-ID>
          <iMSCommunicationServiceIdentifier></iMSCommunicationServiceIdentifier>
          <numberPortabilityRouting></numberPortabilityRouting>
          <transit-IOI-List></transit-IOI-List>
          <mSTimeZone></mSTimeZone>
          <serviceSpecificInfo>
            <serviceSpecificType>0</serviceSpecificType>
            <serviceSpecificData>test-0</serviceSpecificData>
          </serviceSpecificInfo>
          <serviceSpecificInfo>
            <serviceSpecificType>1</serviceSpecificType>
            <serviceSpecificData>test-1</serviceSpecificData>
          </serviceSpecificInfo>
          <requested-Party-Address>
            <sip>sip:requesteduser@requesteddomain.com</sip>
          </requested-Party-Address>
          <list-Of-Called-Asserted-Identity>
            <sip>sip:unknown@unknown</sip>
          </list-Of-Called-Asserted-Identity>
          <mMTelInformation>
            <listOfSupplServices>
              <serviceType>0</serviceType>
              <serviceMode>0</serviceMode>
              <associated-Party-Address>
                <sip>sip:other.party@domain.com</sip>
              </associated-Party-Address>
              <serviceId>0</serviceId>
              <changeTime>031231235959+0000</changeTime>
              <participantActionType>0</participantActionType>
            </listOfSupplServices>
          </mMTelInformation>
        </mMTelRecord>
      </mMTelServiceRecord>
    </layer>
  </CDR>
</callcase>
